version: "3"

services:
  db:
    image: mariadb:10.3
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - aatis_core

  app:
    build:
      context: .
      dockerfile: .boing/docker/app/aatis/Dockerfile
      args:
        PHP_VERSION: "8.2"
    volumes:
      - .:/srv
    networks:
      - aatis_core

networks:
  aatis_core:
    external: true

volumes:
  db_data:
