exclude_paths:
  - '/Kernel.php'
  - '/Entity'

include_services:
  - 'Aatis\Routing\Service\Router'
  - 'Aatis\Tester\Service\Writer'
  - 'Aatis\TemplateRenderer\Service\TemplateRenderer'

services:
  Aatis\Tester\Service\Writer:
    arguments:
      defaultMessage: "Hello World ! "
