excludes:
  - '/Kernel.php'
  - '/Service/ContainerBuilder.php'
  - '/Entity'

services:
# Aatis\Core\Service\Router:
#   environment:
#     - dev
#     - prod
#   arguments:
#     number: 2
#     ch: 'string'
