exclude_paths:
  - '/Kernel.php'
  - '/Entity'

include_services:
  - 'Aatis\Routing\Service\Router'
  - 'Aatis\Tester\Service\Writer'
  - 'Aatis\TemplateRenderer\Service\TemplateRenderer'

services:
  Aatis\Tester\Service\Writer:
    arguments:
      defaultMessage: "Hello World !"

  Aatis\Routing\Service\Router:
    arguments:
      notFoundErrorVars:
        code: 404
        message: "Page not found !"
  
  Aatis\TemplateRenderer\Service\TemplateRenderer:
    arguments:
      extraRenderers:
        - 'Aatis\Tester\Service\TemplateRenderer\ExtraRenderer'
        - 'Aatis\Tester\Service\TemplateRenderer\ZebiRenderer'
